config/routes.rb
Pms::Application.routes.draw do  

  post "project/addproject"

  get "project/index"
  post "project/addtasks"
  post "project/addtask"
  get "project/attachments"  
  get "organization/edit"
  get "project/edit"
  get "project/tedit"  
  get "project/tasks"
  get "project/ctask"    
  post "project/taskedit"
  post "organization/orgedit"
  post "project/prgedit"
  get "project/add"
  get "project/download"  
  post "project/attachment"
  get "organization/result"
  get "project/tresult"  
  get "project/projects"    
  get "organization/home"
  get "organization/odelete"
  get "project/delete"
  get "project/tdelete"
  get "project/bulkcreatetasks"
  get 'organization/autocomplete_org_name'
  post "organization/create"
  get "project/attach"
  get "organization/organizations"
  get "organization/new"
  
  
  match '/tresult',to:"project#tresult"
  match '/result',to:"organization#result" 
  match '/prgedit', to:"project#prgedit"
  match '/projects', to:"project#projects"  
  match '/attachments', to:"project#attachments"    
  match '/edit',to:"project#edit"
  match '/tasks',to:"project#tasks"  
  match '/tedit',to:"project#tedit"
  match '/index',to:"project#index"    
  match '/taskedit',to:"project#taskedit"    
  match '/delete' , to:"project#delete"
  match '/tdelete' , to:"project#tdelete"  
  match '/oedit',to: "organization#oedit"
  match '/orgedit',to: "organization#orgedit"
  match '/create', to:'organization#create'
  match '/attachment', to:'project#attachment'
  match '/addproject',to:'project#addproject'
  match '/addproject',to:'project#addtask'  
  match '/addproject',to:'project#addtasks'
  match '/organizations',to:'organization#organizations' 
  match '/odelete',to:'organization#odelete'   
  match '/home',to:'organization#home'    
  match '/new', to:'organization#new'
  match '/add', to:'project#add' 
  match '/download', to:'project#download'   
  match '/ctask',to:'project#ctask'
  match '/bulkcreatetasks',to:'project#bulkcreatetasks' 
  match '/attach',to:'project#attach'

   root :to => 'organization#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :pname, :ptypeid,:tcount
  
  belongs_to :organization 
  belongs_to :projectype
  has_many :tasks,dependent: :destroy
  

  
  
  
end

app/models/projecttype.rb
class Projecttype < ActiveRecord::Base
  attr_accessible :ptype, :ptypeid
  has_many :projects
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  $prgedit1=""
  $tedit1=""
  def addproject
  
   	@f=Project.new

        # Checking the values of parameters      
        if params[:pname].blank? || params[:orgid]=="Select Organization" || params[:orgid]=="Select project type"
      	
        	return flash[:error] = "Project Not Created"
        end
	
	# Adding project to the Projects table
  	@f.pname=params[:pname]
     	@f.projecttypes_id=params[:ptid]
     	@f.organization_id=params[:orgid]
	
	if @f.save
     		
#     		return flash[:notice] = "Project Created successfully"
		org=Organization.find_by_id(params[:orgid])
		pcountinc=org.pcount+1
		puts "===================="
		puts pcountinc
		org.pcount= pcountinc
		org.save
		flash[:notice] = "#{@f.pname} Project Created successfully"
		redirect_to projects_path
     	else
     		return flash[:error] = "Project Not Created"
  	end
  end
 
  def addtask
  
  	if params[:pid]=="Select Project"

     		return flash[:error] = "Please Choose A Project"
     	elsif params[:tname].empty?
     		return flash[:error] = "Task Not Created"
     	end
  
   		tsk=Task.new  		 			
		tsk.tname=params[:tname]
		tsk.project_id=params[:pid]
	  
	if tsk.save	
	  
		prj=Project.find_by_id(params[:pid])
		tcountinc=prj.tcount+1
		puts "===================="
		puts tcountinc
		prj.tcount= tcountinc
		prj.save
	       	
     		flash[:notice] = "One Task is Created successfully"
		redirect_to tasks_path
	else
	  	return flash[:error] = "Task Not Created"
  	end
	  
	  
	if params[:file]
  		last=Task.find_by_tname(params[:tname])
		id=last.id

        	params[:file].each do |file|

		multiple_attachment=Attachment.new
		multiple_attachment.attachment_name = file.original_filename
		multiple_attachment.task_id=id
		multiple_attachment.attach = file.read()
		multiple_attachment.save
		     
             end
	end
	
  
  end
 
  def addtasks

	a=Array.new
  	a << params[:tname1]
  	a << params[:tname2]
  	a << params[:tname3]  	  	
  	a << params[:tname4]
  	a << params[:tname5]  	  	
  	count=0
  	a.each do |value|
  			if !value.empty?

	  			@p=Task.new  		 			
	  			@p.tname=value
	  			@p.project_id=params[:pid]
				@p.save
				count=count+1
  			end
  	end
  
  		prj=Project.find_by_id(params[:pid])
		  	
  		  	
  	if params[:pid]=="Select Project"

     		return flash[:error] = "Please Choose A Project"

     	elsif count==0
     		
     		return flash[:error] = "Task Not Created"
		
     	elsif count >=1
		
		tcountinc=prj.tcount+count
		prj.tcount= tcountinc
		prj.save
     		
     		 flash[:notice] = "#{count} Tasks are Created successfully"
		 redirect_to tasks_path
  	end
  end
 
  def add
  end
  
  def projects
	
	@search=Project.page(params[:page]).per(3).search(params[:q])
	@project= @search.result	

	@s1=Projecttype.search(params[:q])
	@projecttypes =@s1.result
	
	
 end
  
  def attachment

     # Checking the values of parameters
	if params[:file].blank?
   	
   		return flash[:error] = "Please Choose a File "    

   	elsif params[:pid]=="Select Task"

   		return flash[:error] = "Please Choose a Task "       		
   	end
 
 
      pid= params[:pid]

	attachcount=0     
     params[:file].each do |file|

		multiple_attachment=Attachment.new
		multiple_attachment.attachment_name = file.original_filename
		multiple_attachment.task_id=pid
		multiple_attachment.attach = file.read()
		multiple_attachment.save
		attachcount=attachcount+1			     
     end
	
	if attachcount==0
     		
     		return flash[:error] = "File Not Attached"
     	elsif attachcount==1
     		flash[:notice] = "One File has been Attached successfully..."
     		redirect_to attachments_path
     	else
     		flash[:notice] = "#{attachcount} Files has been Attached successfully..."
     		redirect_to attachments_path     		
  	end     

     end
   
    def download
    
   	 attach_name = params[:name]
	 f = Attachment.find_by_attachment_name(attach_name)
	 send_data f.attach, :filename => "#{attach_name}" , :disposition => 'attachment'
 
    end
     
    def delete
    
	project_name =params[:name]

	prg=Project.find_by_pname(project_name)
	
	if prg.destroy
		org=Organization.find_by_id(prg.organization_id)
		pcountinc=org.pcount-1
		puts "===================="
		puts pcountinc
		org.pcount= pcountinc
		org.save

     		flash[:notice] = " #{prg.pname} Project Deleted Successfully"
		redirect_to projects_path
     	else
     		return flash[:error] = " #{prg.pname} Not Deleted"
  	end
    
    end
    
  
  def edit
  
 	 @prgdetails=Project.find_by_pname(params[:name])
	 $prgedit1=@prgdetails.pname
  end
  
  def prgedit
  
      prg1=Project.find_by_pname($prgedit1)

     # Checking the values of parameters      
      if params[:pname].blank? || params[:orgid]=="Select Organization" || params[:orgid]=="Select project type"
      		
      		return flash[:error] = "Project Not Updated"
      end
	
	# Adding project to the Projects table
  	prg1.pname=params[:pname]
     	prg1.projecttypes_id=params[:ptid]
     	prg1.organization_id=params[:orgid]
	
	if prg1.save

     		flash[:notice] = "#{prg1.pname} Project Updated successfully"
     		redirect_to projects_path
     	else
     		return flash[:error] = "Project Not Updated"
  	end
    
   end
   
   def tresult
   
   	#To Store Selected Project id
        @pid=params[:name].to_i

   	@pname=Project.find_by_id(@pid)
	# to Store organization id
	#@oid=params[:id]

   	if params[:id]
		@pid=params[:id].to_i
	end
	#@tnames=Kaminari.paginate_array(@p).page(params[:page]).per(2)
	@attachsearch=Attachment.page(params[:page]).per(14).search(params[:q])
	@attachment=@attachsearch.result
	#@p=Project.page(params[:page]).per(5)
	
   end

    def tdelete
    
	task_name =params[:name]
	
	task=Task.find_by_tname(task_name)
	if task.destroy
		
		prj=Project.find_by_id(task.project_id)
		tcountinc=prj.tcount-1
		prj.tcount= tcountinc
		prj.save
		
     		flash[:notice] = " #{task.tname}  Deleted"
     		redirect_to tasks_path
     	else
     		return flash[:error] = " #{task.tname} Not Deleted"
  	end
    
    end

  def tedit
  
  	@taskdetails=Task.find_by_tname(params[:name])
  	$tedit1=@taskdetails.tname
  end

 def taskedit
  
      		task1=Task.find_by_tname($tedit1)
	
		task1.tname=params[:tname]  
		task1.project_id=params[:pid]

			if task1.save
				flash[:notice] = "#{task1.tname} is Updated successfully"
				redirect_to tasks_path
			else
		     		return flash[:error] = "Task Not Updated"
		     	end
 end    
 
 before_filter :set_search

  def set_search
  
		@search  = Project.search(params[:q])
		@search1 = Task.search(params[:q])
  end

 def tasks
 
	@search = Task.page(params[:page]).per(6).search(params[:q])
	@pj = @search.result
	
 end
  
def attachments

        @search=Attachment.page(params[:page]).per(6).search(params[:q])
	@attach=@search.result
	#@att=Kaminari.paginate_array(@p1).page(params[:page]).per(3)
 end


end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/add.html.erb
<h1>Create Project</h1>

<%= form_tag({ :controller => "project", :action => 'addproject'}) do %> <!-- Form Begining-->

	<table>
	<tr>
		<td> <label >Project Name* :</label></td>
		<td>  <input type="text" name=pname placeholder="Project Name">   </td>
	</tr>
	<tr>
		<td><label>Organization* : </label></td>
		<td>
			<select title="Select Organization" name="orgid" >
			<option  selected>Select Organization</option>			
			<% s=Organization.find(:all)%> 
			<% s.each do |f|%>
			
				<option name="orgid" value= <%= f.id %> ><%= f.org_name%></option>
			<%end%>
		</td>
	</tr>
	<tr>
		<td><label >Project Type* : </label></td>
		<td>
			<select title="Select project type" name="ptid" >
			<option  selected>Select Project type</option>	
			<% s=Projecttype.find(:all)%> 

			
			<% s.each do |f|%>
			
			<option name="ptid" value= <%= f.id%> ><%= f.ptype%>
			</option><%end%></td>
	</tr>

	</table>
	<%= submit_tag "Create",{:class => 'btn  btn-primary'}  %> 
	<input type="reset"  value="Reset" class="btn btn-inverse" />
	
<% end %> <!-- From Ending-->

app/views/project/addtask.html.erb
<h2> <%=flash[:error]%></h2>
<%= link_to "Back",:back%>

app/views/project/addtasks.html.erb
<h2> <%= flash[:error]%></h2>
<%= link_to "Back",:back%>

app/views/project/attach.html.erb
<head>
<style>
a.close
{
	font-weight:bold;
}

</style>
<script>

$(document).ready(function(){

	
	
	$(".more").click(function(){


		$(".attach").append("<span> <input type='file' name='file[]'> </span>");
	});
	
	

});

</script>
</head>

<h1>Add Attachments</h1>

<div class=span8 offset=2>
<!-- Form Begining-->
<%= form_tag({ :controller => "project", :action => 'attachment'}, :multipart => true) do %> 
<div class="span5">
		<div class="span2"><label>Task* : </label></div>
		
		<div class="span2">
			<select title="Project" name="pid" >
			<option  selected>Select Task</option>			
			<% t=Project.find(:all)%>		
			<% s=Task.find(:all)%> 
	
				<% t.each do |f1|%>
				<% s.each do |f|%>
					<%if f1.id==f.project_id%>
					<option name="pid" value= <%= f.id%>  > <%= f.tname%> </option>
					<%end%>
				<%end%>
				<%end%>	</select>	</div>
</div>

<div class="span6">
		<div class="span2"><label > Select File* :</label> </div>
		
		<div class="span3 attach"><%= file_field_tag 'file[]',:multiple =>:true %>

		</div>
<div class="span4" style="float:right"  > &nbsp; &nbsp;&nbsp;  <a class="more" href="javaScript:void(0)"> Add More Attachments</a></div>		
</div>

<div class="span5">
<div class=span3 ><%= submit_tag "Attach", :class => 'btn  btn-primary' %></div>
</div>
<% end %> <!-- Form Ending-->
</div> <!-- Main Div -->

app/views/project/attachment.html.erb
<h2> <%= flash[:error]%></h2>

<%= link_to "Back",:back%>

app/views/project/attachments.html.erb
<html>
<head>
<style>
table
{
	margin:auto;
}
.mytab {
	width:800px !important;
}
.pull-right
{
	margin-right:100px !important;
}
</style>
</head>
<body>
<% if flash[:notice]%>
<div class="alert alert-success msg" id="msgbox" >
           <a class="close" data-dismiss="alert"  href="#">&times;</a><%= flash[:notice]%> </div>

<%end%>
<h1>Attachments List </h1>



<% q=Organization.find_by_sql"select t.tname,a.attachment_name from tasks t left join attachments a on t.id=a.task_id;"%>

<div class="btn-toolbar">

<%= link_to "Create Attachments ",attach_path , class: "btn btn-primary" %>

</div>

<div class="well mytab">
    <table  class="table table-striped table-hover mytab" id="example">
      <thead>
        <tr >	
        	<th> <%= sort_link(@search, :task_tname, "Task Name")%></th>
		<th > <%= sort_link(@search, :attachment_name, "Attachment")%> </th>
	</tr>
	</thead>
      <tbody>
		      
	<% @attach.each do |att|%>
        <tr>
          <td><%= att.task.try(:tname)%></td>

		<td>
		
<%= link_to att.attachment_name,download_path(:name=>att.attachment_name),:title=>"Click To Download Attachment" %> 
			
		</td>
		
	</tr>
				<%end%>
						
	</tbody>	
</table>

<%= paginate @attach, :window => 2  %>
</div>
</body>
</html>			

app/views/project/ctask.html.erb
<head>
<style>
.attach
{
	margin-left:40px !important;
}
.span4
{
	margin-bottom:10px;
}
.buttons
{
		margin-left:20px !important;
}

</style>
<script>

$(document).ready(function(){

	
	
	$(".more").click(function(){


		$(".attach").append("<span> <input type='file' name='file[]'> </span>");
	});
	
	

});

</script>
</head>
<p>
<h1 style="display:inline;margin:0px 240px 10px 350px !important " >Create Tasks</h1>
<%= link_to "Bulk Creation ",bulkcreatetasks_path , class: "btn btn-primary link1" %>
</p>
<%= form_tag({ :controller => "project", :action => 'addtask'}, :multipart => true) do %>

	<table>
	<tr>
		<td> <label >Task * : </label></td>
		<td> <input type="text" name=tname placeholder="Task Name"> </td>
	</tr>

	<tr>
		<td><label>Project* : </label></td>
		<td>
			<select title="Project" name="pid" >
			<option  selected>Select Project</option>			
			<% s=Project.find(:all)%> 

			
			<% s.each do |f|%>
			
			<option name="pid" value= <%= f.id%>  > <%= f.pname%>
			</option><%end%></td>
	</tr>
	</table>
<div class="span6">
<div class="span3 attach"><%= file_field_tag 'file[]',:multiple =>:true %></div>
<div class="span4"   > &nbsp; &nbsp;&nbsp;  <a class="more" href="javaScript:void(0)"> Add More Attachments</a></div>
</div>	
</div>
<div class="buttons">
	<div class="span1" offset=2><%= submit_tag "Create",{:class => 'btn  btn-primary'}  %> </div><div class="span1"><input type="reset"  value="Reset" class="btn btn-inverse" /></div>
</div>	
<% end %>

app/views/project/delete.html.erb
<h2> <%= flash[:error]%></h2>


<%= link_to "Back",projects_path%>

app/views/project/edit.html.erb
<h1>Update Project</h1>

<%= form_tag({ :controller => "project", :action => 'prgedit'}) do %> <!-- Form Begining-->

	<table>
	<tr>
		<td> <label >Project Name* :</label></td>
		<td>  <input type="text" name=pname placeholder="Project Name" value="<%= @prgdetails.pname %>">   </td>
	</tr>
	<tr>
		<td><label>Organization* : </label></td>
		<td>
			<select title="Select Organization" name="orgid" >
			<option>Select Organization</option>			
			<% s=Organization.find(:all)%> 
			<% s.each do |f|%>
			
				<% if f.id== @prgdetails.organization_id %>
	
					<option name="orgid" value= <%= f.id %> selected><%= f.org_name%></option>				
				<%else%>
					<option name="orgid" value= <%= f.id %> ><%= f.org_name%></option>
				<%end%>
				
			<%end%>
		</td>
	</tr>
	<tr>
		<td><label >Project Type* : </label></td>
		<td>
			<select title="Select project type" name="ptid" >
			<option  selected>Select Project type</option>	
			<% s=Projecttype.find(:all)%> 

			
			<% s.each do |f|%>
			<% if f.id== @prgdetails.projecttypes_id %>

				<option name="ptid" value= <%= f.id%> selected><%= f.ptype%>
			<%else%>
				<option name="ptid" value= <%= f.id%> ><%= f.ptype%></option>
			<%end%>
			<%end%>
		</td>
	</tr>

	</table>
	<%= submit_tag "Update",{:class => 'btn  btn-primary'}  %> 
	<%=link_to "Back",:back, :class=>"btn btn-inverse" %>
	
<% end %> <!-- From Ending-->

app/views/project/prgedit.html.erb
<h2> <%= flash[:error]%></h2>

<%= link_to "Back",:back%>

app/views/project/projects.html.erb
<html>

<head>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

<script>

 $(function() {
       
    var t =$("#hide").val();
    var array = t.split('"');                        
    
    var availableTags = [ ];
    $( "#tags" ).autocomplete({
      source: array
    });
  });

</script>
<script>
 $(function() {
       
    var t =$("#hide").val();
    var array = t.split('"');                        
    
    var availableTags = [ ];
    $( "#tags" ).autocomplete({
      source: array
    });
  });

</script>
</head>
<body>

<% if flash[:notice]%>
<div class="alert alert-success msg" id="msgbox" >
           <a class="close" data-dismiss="alert"  href="#">&times;</a><%= flash[:notice]%> </div>

<%end%>

  
<h1 style="clear:both">Projects Details</h1>

<div class="btn-toolbar">
<%= link_to "Create a Project",add_path , class: "btn btn-primary" %>

</div>


<div class="well">
    <table class="table table-striped table-hover display"  id="example"  >
      <thead>
        <tr>
        
          <th><%= sort_link(@search,:pname,"Project Name")%></th>
          <th><%= sort_link(@search,:ptype,"Project Type")%></th>
          <th><%= sort_link(@search,:tcount,"No.Of Tasks")%></th>
          <th ><%=link_to "Operations",'#'%></th>
         
        </tr>
      </thead>
      <tbody>

      <% @project.each do |ps| %>
      	<% @projecttypes.each do |pt| %>
       <%if(ps.projecttypes_id == pt.id )%>	
        <tr>
         
          <td><%= ps.pname%></td>
           <td><%= pt.ptype%></td>
	          <td >&nbsp; &nbsp; &nbsp; <%= link_to ps.tcount,tresult_path(:name=>ps.id),:title=>"Click to View Task"%></td>

<td><%= link_to "Edit",edit_path(:name=>ps.pname), class: "btn btn-primary"%>&nbsp; <%= link_to "Delete",delete_path(:name=>ps.pname), class: "btn btn-danger" ,:confirm => "Are You sure?"%></td>
          
        </tr>
          
    <%  end %>
        <%  end %>
            <%  end %>
      </tbody>
    </table>
    
    	<%a=Array.new%>
	<%o=Project.all%>
	<%o.each do |t|%>
		<%a << t.pname%>
		<% if !a.include?(t.ptype) %>		
			<%a << t.ptype%>
		<%end%>
		<%a << t.tcount.to_s %>
	<%end%>

        <input type=hidden id="hide" value= "'<%=a.map(&:inspect).join('')%>'"/>    
</div>
<%= paginate @project, :window => 2  %>
</body>
</html>			

app/views/project/taskedit.html.erb
<h2> <%= flash[:error]%></h2>
<%= link_to "Back",:back%>

app/views/project/tasks.html.erb
<html>
<head>
<style>
</style>
</head>
<body>
<% if flash[:notice]%>
<div class="alert alert-success msg" id="msgbox" >
           <a class="close" data-dismiss="alert"  href="#">&times;</a><%= flash[:notice]%> </div>

<%end%>


<h1 style="clear:both">List of all Tasks</h1>



<div class="btn-toolbar">

<%= link_to "Create Task ",ctask_path , class: "btn btn-primary" %>

</div>

<div class="well">
    <table  class="table table-striped table-hover" id="example">
      <thead>
        <tr >
          <th ><%= sort_link(@search, :project_pname, "Project Name")%></th>
          <th ><%= sort_link(@search, :tname, "Task Name")%></th>
            <th colspan=2><%=link_to "Operations",'#'%></th>
          
        </tr>
      </thead>
      <tbody>
		      
	<% @pj.each do |tsk|%>
        <tr>
          <td><%= tsk.project.try(:pname)%></td>
          <td ><%= tsk.tname%> </td>
          <td>
	      <%=link_to "Edit",tedit_path(:name=>tsk.tname), class: "btn btn-primary"%> &nbsp; 
		 <%= link_to "Delete",tdelete_path(:name=>tsk.tname), class: "btn btn-danger" ,:confirm => "Are You sure?"%>
         </td>
        </tr>
        <%end%>
      </tbody>
    </table>
    <%= paginate @pj, :window=>2 %>
</div>



</html>			

app/views/project/tdelete.html.erb
<h2> <%= flash[:error]%></h2>