config/routes.rb
Pms::Application.routes.draw do  

  post "project/addproject"

  get "project/index"
  post "project/addtasks"
  post "project/addtask"
  get "project/attachments"  
  get "organization/edit"
  get "project/edit"
  get "project/tedit"  
  get "project/tasks"
  get "project/ctask"    
  post "project/taskedit"
  post "organization/orgedit"
  post "project/prgedit"
  get "project/add"
  get "project/download"  
  post "project/attachment"
  get "organization/result"
  get "project/tresult"  
  get "project/projects"    
  get "organization/home"
  get "organization/odelete"
  get "project/delete"
  get "project/tdelete"
  get "project/bulkcreatetasks"
  get 'organization/autocomplete_org_name'
  post "organization/create"
  get "project/attach"
  get "organization/organizations"
  get "organization/new"
  
  
  match '/tresult',to:"project#tresult"
  match '/result',to:"organization#result" 
  match '/prgedit', to:"project#prgedit"
  match '/projects', to:"project#projects"  
  match '/attachments', to:"project#attachments"    
  match '/edit',to:"project#edit"
  match '/tasks',to:"project#tasks"  
  match '/tedit',to:"project#tedit"
  match '/index',to:"project#index"    
  match '/taskedit',to:"project#taskedit"    
  match '/delete' , to:"project#delete"
  match '/tdelete' , to:"project#tdelete"  
  match '/oedit',to: "organization#oedit"
  match '/orgedit',to: "organization#orgedit"
  match '/create', to:'organization#create'
  match '/attachment', to:'project#attachment'
  match '/addproject',to:'project#addproject'
  match '/addproject',to:'project#addtask'  
  match '/addproject',to:'project#addtasks'
  match '/organizations',to:'organization#organizations' 
  match '/odelete',to:'organization#odelete'   
  match '/home',to:'organization#home'    
  match '/new', to:'organization#new'
  match '/add', to:'project#add' 
  match '/download', to:'project#download'   
  match '/ctask',to:'project#ctask'
  match '/bulkcreatetasks',to:'project#bulkcreatetasks' 
  match '/attach',to:'project#attach'

   root :to => 'organization#home'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :name, :org_name, :pcount
  validates_uniqueness_of :org_name
  has_many :projects,dependent: :destroy
end

app/controllers/organization_controller.rb
class OrganizationController < ApplicationController
$orgedit1=""
  def home
  end

  def create
  
        
      # Checking the values of parameters
      if params[:organization]["org_name"].blank? || params[:organization]["name"].blank?
      	  		return flash[:error] = "Organization Not Created"
      end
     
      @organization = Organization.create(params[:organization])
     
     	if @organization
     		flash[:notice] = "#{params[:organization]["org_name"]}Organization Created successfully"
     		redirect_to organizations_path
     	else
     		return flash[:error] = "Organization Not Created"
  	end
  end
  
  def odelete
  	
	
	organization_name =params[:name]
	
	org=Organization.find_by_org_name(organization_name)
	if org.destroy
		
     		flash[:notice] = " #{org.org_name} Organization Deleted"
		redirect_to organizations_path
     	else
     		return flash[:error] = " #{org.org_name} Organization Not Deleted"
  	end

  end
  
  def oedit
  	@orgdetails=Organization.find_by_org_name(params[:name])
	  $orgedit1=@orgdetails.org_name
  end
  
  def orgedit
  
     # Creating Organization
 
     @org1=Organization.find_by_org_name($orgedit1)

     # Checking the values of parameters
      if params[:name].blank? || params[:orgname].blank?
      	
      		return flash[:error] = "Organization Not Updated"
      end
    
     @org1.name = params[:name]
     @org1.org_name= params[:orgname]
     
     	if @org1.save
     		
     		 flash[:notice] = "#{@org1.name} Updated successfully"
     		 redirect_to organizations_path
     	else
     		return flash[:error] = "Organization Not Updated"
  	end  
  
  end
  
  def organizations
  
	@search=Organization.page(params[:page]).per(6).search(params[:q])
	@org = @search.result
	@a=Array.new
	puts "=========================="
	
	o=Organization.all
	o.each do |t|
	@a << t.org_name
	@a << t.pcount.to_s 
	end
#	puts @a.map(&:inspect).join(', ').class

	puts "=========================="
  end
  def result
  
	  @oname=params[:name]
   
	  @v=@oname.to_i
  
 	 if params[:id]
		@v=params[:id].to_i
   	 end
  	
	  @search = Project.page(params[:page]).per(12).search(params[:q])
	  @project=@search.result
	  @projecttypes = Projecttype.all

   end
   
  def new
  end
end

app/helpers/organization_helper.rb
module OrganizationHelper
end

app/views/organization/create.html.erb
<h2> <%= flash[:error]%></h2>
<%=link_to "Back",:back%>

app/views/organization/home.html.erb
<head>
<style>
	body
	{
		margin-top:10px;
		background-color:white;
	}
</style>
</head>

<div class="center hero-unit">
  <h1>Project Management System</h1>

  <h3>
    Welcome to PMS Here you can add projects by creating an Organization
  </h3>

  <%= link_to "Create an Organization",new_path , class: "btn btn-large btn-primary" %>
</div>

app/views/organization/new.html.erb
<h1>Create Organization</h1>

<%= form_tag({ :controller => "organization", :action => 'create'}, :name=>'organization') do %>

	<table>
	<tr>
		<td><label >Full Name* : </label></td>
		<td><input type=text name='organization[name]' id=orgname placeholder="Name" /></td>		
	</tr>
	<tr>

		<td> <label >Organization Name* :</label></td>
		<td>  <input type=text name='organization[org_name]' id=name placeholder="Organization Name" />    </td>
	</tr>
	</table>
	<%= submit_tag "Create",{:class => 'btn  btn-primary'}  %> <input type="reset"  value="Reset" class="btn btn-inverse" />
	
<% end %>

app/views/organization/odelete.html.erb
<h2> <%= flash[:error]%></h2>

<%= link_to "Back",organizations_path%>

app/views/organization/oedit.html.erb
<h1>Update Organization</h1>

<%= form_tag({ :controller => "organization", :action => 'orgedit'}) do %>

	<table>
	<tr>
		<td> <label>Full Name* :</label></td>
		<td>  <input type=text name=name id=name placeholder="Name" value= "<%= @orgdetails.name %>" />    </td>
	</tr>
	<tr>
		<td><label >Organization Name* : </label></td>
		<td><input type=text name=orgname id=orgname placeholder="Organization Name" value= "<%= @orgdetails.org_name%>" /></td>
	</tr>
	</table>
	<%= submit_tag "Update",{:class => 'btn  btn-primary'}  %>  <%=link_to "Back",:back, :class=>"btn btn-inverse" %>
	
<% end %>

app/views/organization/organizations.html.erb
<html>
<head>

 <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />

<script>
$(function() {
var availableTags = [
"ActionScript",
"AppleScript",
"Asp",
"BASIC",
"C",
"C++",
"Clojure",
"COBOL",
"ColdFusion",
"Erlang",
"Fortran",
"Groovy",
"Haskell",
"Java",
"JavaScript",
"Lisp",
"Perl",
"PHP",
"Python",
"Ruby",
"Scala",
"Scheme"
];
function split( val ) {
return val.split( /,\s*/ );
}
function extractLast( term ) {
return split( term ).pop();
}
$( "#tagss" )
// don't navigate away from the field on tab when selecting an item
.bind( "keydown", function( event ) {
if ( event.keyCode === $.ui.keyCode.TAB &&
$( this ).data( "ui-autocomplete" ).menu.active ) {
event.preventDefault();
}
})
.autocomplete({
minLength: 0,
source: function( request, response ) {
// delegate back to autocomplete, but extract the last term
response( $.ui.autocomplete.filter(
availableTags, extractLast( request.term ) ) );
},
focus: function() {
// prevent value inserted on focus
return false;
},
select: function( event, ui ) {
var terms = split( this.value );
// remove the current input
terms.pop();
// add the selected item
terms.push( ui.item.value );
// add placeholder to get the comma-and-space at the end
terms.push( "" );
this.value = terms.join( ", " );
return false;
}
});
});
</script>


</head>
<body>

<% if flash[:notice]%>
<div class="alert alert-success msg" id="msgbox" >
           <a class="close" data-dismiss="alert"  href="#">&times;</a><%= flash[:notice]%> </div>

<%end%>


<h1 style="clear:both">List of all Organizations</h1>



<div class="btn-toolbar">

<%= link_to "Create an Organization ",new_path , class: "btn btn-primary" %>

</div>

<div class="well">
    <table  class="table table-striped table-hover">
      <thead>
        <tr >
        <th> <%= sort_link(@search, :org_name, "Organization Name") %> </th>
            <th><%= sort_link(@search,:pcount,"No.of Projects") %></th>
            <th colspan=2><%=link_to "Operations",'#'%></th>
         </tr>
      </thead>
      <tbody>

	<% @org.each do |o| %>
      
        <tr>
          <td> <%= o.org_name%></td>
               
          
          <td >&nbsp; &nbsp; &nbsp; <%= link_to o.pcount,result_path(:name=>o.id),:title=>"Click to View Projects"%></td>
          <td>
	      <%=link_to "Edit",oedit_path(:name=>o.org_name), class: "btn btn-primary"%> &nbsp;
<%= link_to "Delete",odelete_path(:name=>o.org_name) , class: "btn btn-danger",:confirm => "Are You sure?"%>
         </td>
        </tr>
        <%end%>
        
      </tbody>
    </table>
        <input type=hidden id="hide" value= "<%=@a%>;"/>
</div>
<%= paginate @org, :window => 2  %>
</body>
</html>			

app/views/organization/orgedit.html.erb
<h2> <%= flash[:error]%></h2>

<%= link_to "Back",organizations_path%>

app/views/organization/result.html.erb
<html>

<body>


<h1> Projects List </h1>


<div class="btn-toolbar">
<%= link_to "Create a Project",add_path , class: "btn btn-primary" %>

</div>

<div class="well">
<table class="table table-striped table-hover" >
	
	<thead>
	<tr>
          <th><%= sort_link(@search,:pname,"Project Name",:id=>@v)%></th>
          <th><%= sort_link(@search,:projecttypes_id,"Project Type",:id=>@v)%></th>
          <th><%= sort_link(@search,:tcount,"No.Of Tasks",:id=>@v)%></th>
          <th colspan=2><%=link_to "Operations",'#'%></th>

	</tr>
	</thead>
	<tbody>


		
			<% @project.each do |ps|%>
		      		 <%if ps.organization_id==@v%>	
      			<%@projecttypes.each do |pt|%>
		       <%if(ps.projecttypes_id == pt.id && ps.organization_id==@v)%>
		<tr>			
			<td><%=ps.pname%></td>
			<td><%=pt.ptype%></td>
			<td class="pad">&nbsp; &nbsp; &nbsp; 

				<%= link_to ps.tcount,tresult_path(:name=>ps.id),:title=>"Click to View Tasks"%> </div> 
					
			
			</td>
			<td><%= link_to "Edit",edit_path(:name=>ps.pname), class: "btn btn-primary"%> &nbsp;
			<%= link_to "Delete",delete_path(:name=>ps.pname) , class: "btn btn-danger",:confirm => "Are You sure?"%></td>
			
			
	</tr>
			<%end%>
			<%end%>
			<%end%>
			<%end%>	
				
	</tbody>
</table>

</div>
<%= paginate @project,:window=>2%>
<%= link_to "Back",organizations_path,:class=>"btn"%>
</body>
</html>			