config/routes.rb
Pms::Application.routes.draw do  

  post "project/addproject"

  get "project/index"
  post "project/addtasks"
  post "project/addtask"
  get "project/attachments"  
  get "organization/edit"
  get "project/edit"
  get "project/tedit"  
  get "project/tasks"
  get "project/ctask"    
  post "project/taskedit"
  post "organization/orgedit"
  post "project/prgedit"
  get "project/add"
  get "project/download"  
  post "project/attachment"
  get "organization/result"
  get "project/tresult"  
  get "project/projects"    
  get "organization/home"
  get "organization/odelete"
  get "project/delete"
  get "project/tdelete"
  get "project/bulkcreatetasks"
  get 'organization/autocomplete_org_name'
  post "organization/create"
  get "project/attach"
  get "organization/organizations"
  get "organization/new"
  
  
  match '/tresult',to:"project#tresult"
  match '/result',to:"organization#result" 
  match '/prgedit', to:"project#prgedit"
  match '/projects', to:"project#projects"  
  match '/attachments', to:"project#attachments"    
  match '/edit',to:"project#edit"
  match '/tasks',to:"project#tasks"  
  match '/tedit',to:"project#tedit"
  match '/index',to:"project#index"    
  match '/taskedit',to:"project#taskedit"    
  match '/delete' , to:"project#delete"
  match '/tdelete' , to:"project#tdelete"  
  match '/oedit',to: "organization#oedit"
  match '/orgedit',to: "organization#orgedit"
  match '/create', to:'organization#create'
  match '/attachment', to:'project#attachment'
  match '/addproject',to:'project#addproject'
  match '/addproject',to:'project#addtask'  
  match '/addproject',to:'project#addtasks'
  match '/organizations',to:'organization#organizations' 
  match '/odelete',to:'organization#odelete'   
  match '/home',to:'organization#home'    
  match '/new', to:'organization#new'
  match '/add', to:'project#add' 
  match '/download', to:'project#download'   
  match '/ctask',to:'project#ctask'
  match '/bulkcreatetasks',to:'project#bulkcreatetasks' 
  match '/attach',to:'project#attach'

   root :to => 'organization#home'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "PMS", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Organizations", organizations_path %></li>          
          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Tasks", tasks_path %></li>
          <li><%= link_to "Attachments", attachments_path %></li>          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PMS</title>
    <%= stylesheet_link_tag    "application", media: "all" %>

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>